version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend-00013940
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: ec2-user
